import {StyleSheet, Dimensions} from 'react-native';

const height = Dimensions.get('window').height;

export default StyleSheet.create({
  topStatusBar: {
    flex: 0,
    backgroundColor: '#303371',
  },
  bottomStatusBar: {
    flex: 1,
    backgroundColor: '#15173e',
  },
  body: {
    backgroundColor: '#303371',
    height: '100%',
    overflow: 'hidden',
  },
  main: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    zIndex: 9999,
    display: 'flex',
    alignItems: 'center',
    paddingTop: 70,
  },
  photo: {
    marginTop: 100,
  },
  name: {
    color: '#ffffff',
    fontFamily: 'Roboto-Bold',
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 0.5,
    lineHeight: 20,
    marginTop: 26,
  },
  productsNumberWrapper: {
    paddingVertical: 5,
    paddingLeft: 15,
    paddingRight: 17,
    borderRadius: 15,
    backgroundColor: '#ffffff',
    marginTop: 26,
  },
  productsNumber: {
    color: '#000000',
    fontFamily: 'Roboto-Regular',
    fontSize: 14,
    fontWeight: '400',
    letterSpacing: 0.39,
    lineHeight: 20,
  },
  card: {
    zIndex: 9999,
    backgroundColor: '#ffffff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: 250,
    height: 360,
    borderRadius: 20,
    paddingTop: 65,
    paddingBottom: 45,
    shadowColor: '#303371',
    shadowOpacity: 0.3,
    shadowRadius: 20,
    shadowOffset: {
      height: 30,
      width: 1,
    },
  },
  test: {
    display: 'flex',
    alignItems: 'center',
  },
  cardImage: {
    marginTop: -115,
  },
  cardTitle: {
    color: '#4e5b76',
    fontFamily: 'Roboto-Bold',
    fontSize: 25,
    fontWeight: '700',
    letterSpacing: 0.69,
    lineHeight: 30,
    textAlign: 'center',
    paddingHorizontal: 40,
  },
  cardText: {
    color: '#a0a9b8',
    fontFamily: 'Roboto-Regular',
    fontSize: 14,
    fontWeight: '400',
    letterSpacing: 0.39,
    lineHeight: 20,
    textAlign: 'center',
    marginTop: 20,
    paddingHorizontal: 40,
  },
  cardButton: {
    backgroundColor: '#303371',
    borderRadius: 19,
    paddingHorizontal: 35,
    paddingVertical: 9,
    // alignSelf: 'flex-end',
  },
  cardButtonText: {
    color: '#ffffff',
    fontFamily: 'Roboto-Bold',
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 0.39,
    lineHeight: 20,
  },
  menu: {
    width: '100%',
    position: 'absolute',
    left: 0,
    bottom: -120,
    display: 'flex',
    flexDirection: 'row',
    backgroundColor: '#ffffff',
    paddingTop: 26,
    paddingBottom: 46,
  },
  menuElement: {
    width: '33.33%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuElementText: {
    color: '#a0a9b8',
    fontFamily: 'Roboto',
    fontSize: 12,
    fontWeight: '400',
    lineHeight: 20,
    marginTop: 5,
  },
  blackColor: {
    color: '#000000',
  },
  lightBlue2Bg: {
    position: 'absolute',
    top: 0,
    left: 0,
  },
  lightBlueBg: {
    position: 'absolute',
    width: '100%',
    top: '25%',
    left: 0,
  },
  greenBg: {
    position: 'absolute',
    width: '100%',
    top: '18%',
    right: 0,
  },
  pinkBg: {
    position: 'absolute',
    width: '100%',
    top: '42%',
    right: 0,
  },
  darkestBlueBg: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    top: '35%',
    left: 0,
  },
  rectangleBg: {
    position: 'absolute',
    width: '100%',
    top: height - 40,
    left: 0,
  },
});
